from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton
DINO = InlineKeyboardButton(text='ДИНОООО', callback_data='DINO')
KB = InlineKeyboardMarkup(row_width=1).add(DINO)

CANCEL = InlineKeyboardButton(text='отмена ❌', callback_data='CANCEL')
BUY = InlineKeyboardButton(text='преобрести ✅', callback_data='BUY')
Buy_menu = InlineKeyboardMarkup(row_width=1).add(BUY).add(CANCEL)

Amoney = InlineKeyboardButton(text='изменить количество баксов 💰', callback_data='change_money')
Adiamond = InlineKeyboardButton(text='изменить количество алмазов 💎', callback_data='change_diamond')
ABD = InlineKeyboardButton(text='вызвать БД', callback_data='BASE')

apanel = InlineKeyboardMarkup(row_width=1).add(Amoney).add(Adiamond).add(ABD)

gamepass1 = InlineKeyboardButton(text='Купить +1 click_multi', callback_data='buy_click_multi')
gamepass2 = InlineKeyboardButton(text='Купить +1 gold_multi', callback_data='buy_gold_multi')
gamepass3 = InlineKeyboardButton(text='Купить +1 diamond_multi', callback_data='buy_diamond_multi')

DONATE = InlineKeyboardMarkup(row_width=1).add(gamepass1).add(gamepass2).add(gamepass3)

BUYp1 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYp1')
Buy_menup1 = InlineKeyboardMarkup(row_width=1).add(BUYp1).add(CANCEL)
BUYp2 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYp2')
Buy_menup2 = InlineKeyboardMarkup(row_width=1).add(BUYp2).add(CANCEL)
BUYp3 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYp3')
Buy_menup3 = InlineKeyboardMarkup(row_width=1).add(BUYp3).add(CANCEL)
BUYd1 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd1')
Buy_menud1 = InlineKeyboardMarkup(row_width=1).add(BUYd1).add(CANCEL)
BUYd2 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd2')
Buy_menud2 = InlineKeyboardMarkup(row_width=1).add(BUYd2).add(CANCEL)
BUYd3 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd3')
Buy_menud3 = InlineKeyboardMarkup(row_width=1).add(BUYd3).add(CANCEL)
BUYd4 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd4')
Buy_menud4 = InlineKeyboardMarkup(row_width=1).add(BUYd4).add(CANCEL)
BUYd5 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd5')
Buy_menud5 = InlineKeyboardMarkup(row_width=1).add(BUYd5).add(CANCEL)
BUYd6 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd6')
Buy_menud6 = InlineKeyboardMarkup(row_width=1).add(BUYd6).add(CANCEL)
BUYd7 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd7')
Buy_menud7 = InlineKeyboardMarkup(row_width=1).add(BUYd7).add(CANCEL)
BUYd8 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd8')
Buy_menud8 = InlineKeyboardMarkup(row_width=1).add(BUYd8).add(CANCEL)
BUYd9 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd9')
Buy_menud9 = InlineKeyboardMarkup(row_width=1).add(BUYd9).add(CANCEL)
BUYd10 = InlineKeyboardButton(text='преобрести ✅', callback_data='BUYd10')
Buy_menud10 = InlineKeyboardMarkup(row_width=1).add(BUYd10).add(CANCEL)
